export const strafenData = {
    info: {
        kassenwart: "Tim Kehrer",
        stvKassenwart: "Christian Sommer",
        paypal: "paypal.me/SGIggMeck2",
        letzteAktualisierung: "15.08.2026"
    },
    // SPIELERLISTE FÜR DAS DROPDOWN
    spieler: [
        "Carsten", "Chris", "Fabi", "Gordon", "Harry", "Jannis", "Janton", "Jonathan", 
        "Josh", "Jule", "Jööl", "Len", "Löwe", "Marlon", "Mateo", "Melf", "Nils", "Nille",
        "Patrick", "Perez", "Rene", "Simon", "Sommer", "Tim"
    ],
    aemter: [
        { amt: "Musik", name: "Fabian & Nils" },
        { amt: "Eisbox", name: "Jannis (Jule)" },
        { amt: "Mannschaftskasse", name: "Harry (Summertime)" },
        { amt: "Trikotliste", name: "Pérez" },
        { amt: "Bier & Turmwächter", name: "Nils (Pérez)" },
        { amt: "Kioskplan", name: "Tim" },
        { amt: "Fußball", name: "Len" },
        { amt: "Kulturwart", name: "Mateo & Marlon" },
        { amt: "Abschlussfahrt", name: "Fabi & Gordon" },
        { amt: "Social Media", name: "Melf & Nils" },
        { amt: "Sekt & Becher", name: "Jöööllll" },
        { amt: "Kapitän", name: "Fabi & Jonathan" }
    ],
    strafen: [
        { kat: "Allgemein", text: "Saisonbeitrag (einmalig)", strafe: "100 € / 70 € (ermäßigt)" },
        { kat: "Allgemein", text: "Sachen in der Halle vergessen (max. 10€)", strafe: "2,00 € / Teil" },
        { kat: "Allgemein", text: "Kasten vergessen", strafe: "1 Kasten" },
        { kat: "Allgemein", text: "Geburtstag / Zeitung", strafe: "1 Kasten" },
        { kat: "Allgemein", text: "Bier verschüttet", strafe: "5,00 €" },
        { kat: "Allgemein", text: "Amt vergessen (Fußball, Eisbox, etc.)", strafe: "3,00 €" },
        { kat: "Allgemein", text: "Kassen/Kioskdienst vergessen (kein Ersatz)", strafe: "30,00 €" },
        { kat: "Training", text: "Zu spät zum Training (max. 10€)", strafe: "1,00 € / min" },
        { kat: "Training", text: "Zu spätes Abmelden (2h telefonisch / 72h WhatsApp)", strafe: "10,00 €" },
        { kat: "Training", text: "Unentschuldigt gefehlt", strafe: "15,00 €" },
        { kat: "Training", text: "Leibchen vergessen", strafe: "2,00 €" },
        { kat: "Training", text: "Handy während Training", strafe: "5,00 €" },
        { kat: "Spiel", text: "Zu spät zum Treffpunkt (max. 15€)", strafe: "2,00 € / min" },
        { kat: "Spiel", text: "Zu spätes Abmelden (24h vorher telefonisch/persönlich)", strafe: "15,00 €" },
        { kat: "Spiel", text: "Unentschuldigt beim Spiel gefehlt", strafe: "50,00 €" },
        { kat: "Spiel", text: "2min wegen Undiszipliniertheit", strafe: "10,00 €" },
        { kat: "Spiel", text: "Respektlos zu Spieler, Trainer, Schiri, Fans", strafe: "40,00 €" },
        { kat: "Spiel", text: "Rot wegen Undiszipliniertheit", strafe: "50,00 € + Kabinenfest" },
        { kat: "Spiel", text: "Warmmachshirt vergessen", strafe: "2,00 €" },
        { kat: "Spiel", text: "Sachen beim Gegner vergessen", strafe: "5,00 € + Kasten (Gegner)" },
        { kat: "Spiel", text: "Trikots vergessen", strafe: "70,00 € + Kabinenfest" },
        { kat: "Spiel", text: "Rauchen/Trinken im Trikot", strafe: "5,00 €" },
        { kat: "Spiel", text: "Heber verworfen / Aufsetzer übers Tor", strafe: "2,00 €" },
        { kat: "Spiel", text: "Torhütertor / 30. Tor", strafe: "1 Kasten" },
        { kat: "Spiel", text: "40. Tor", strafe: "Kabinenfest + Trainerkasten" }
    ]
};

export const kioskData = [
    { staffel: "M-BZK-2 (SG3)", gegner: "SG LaFt", datum: "06.09.2026", uhrzeit: "14:00", kasse: "Tim", kiosk: ["Josh", "Patrick", "Jonathan", "Rene"], halle: "Iggelheim" },
    { staffel: "M-OL (SG1)", gegner: "O.-Hilbersheim", datum: "19.09.2026", uhrzeit: "19:00", kasse: "Tim", kiosk: ["Jannis", "Patrick", "Fabi", "Julian"], halle: "Iggelheim" },
    { staffel: "M-BZK-2 (SG3)", gegner: "TV Thaleischw.", datum: "04.10.2026", uhrzeit: "14:00", kasse: "Tim", kiosk: ["Josh", "Melf", "Fabi", "Jule"], halle: "Iggelheim" },
    { staffel: "M-OL (SG1)", gegner: "TSV Speyer", datum: "08.11.2026", uhrzeit: "18:00", kasse: "Simon", kiosk: ["Jannis", "Len", "Janton", "Jule"], halle: "Iggelheim" },
    { staffel: "M-BZK-2 (SG3)", gegner: "TSV Kandel 2", datum: "22.11.2026", uhrzeit: "14:00", kasse: "Simon", kiosk: ["Sommer", "Rene", "Löwe", "Len"], halle: "Iggelheim" },
    { staffel: "M-BZK-2 (SG3)", gegner: "HSG Greth/Maxd", datum: "06.12.2026", uhrzeit: "18:00", kasse: "Simon", kiosk: ["Marlon", "Mateo", "Nils", "Julian"], halle: "Iggelheim" },
    { staffel: "M-BZK-2 (SG3)", gegner: "Lingenf/Schweg 2", datum: "24.01.2027", uhrzeit: "14:00", kasse: "Harry", kiosk: ["Sommer", "Melf", "Janton", "Nils"], halle: "Iggelheim" },
    { staffel: "M-BZK-2 (SG3)", gegner: "TuS Neuhofen 2", datum: "13.02.2027", uhrzeit: "17:00", kasse: "Harry", kiosk: ["Löwe", "Nils O.", "Jonathan", "Len"], halle: "Meckenheim" },
    { staffel: "M-OL (SG1)", gegner: "MSG KL/Dans", datum: "28.02.2027", uhrzeit: "18:00", kasse: "Harry", kiosk: ["Perez", "Nils", "Fabi", "Melf"], halle: "Iggelheim" },
    { staffel: "M-BZK-2 (SG3)", gegner: "TV Offenbach 4", datum: "20.03.2027", uhrzeit: "16:00", kasse: "Jule", kiosk: ["Perez", "Jonathan", "Mateo", "Jannis"], halle: "Meckenheim" },
    { staffel: "M-BZK-2 (SG3)", gegner: "TuS Heiligenst 2", datum: "17.04.2027", uhrzeit: "15:00", kasse: "Janton", kiosk: ["Perez", "Mateo", "Sommer", "Löwe"], halle: "Iggelheim" }
];

export const bierData = [
    { name: "Nils", date: "2026-08-30" },
    { name: "Jööl", date: "2026-09-01" },
    { name: "Jannis", date: "2026-09-03" },
    { name: "Melf", date: "2026-09-06" },
    { name: "Jonathan", date: "2026-09-08" },
    { name: "Tim", date: "2026-09-10" },
    { name: "Jule", date: "2026-09-12" },
    { name: "Len", date: "2026-09-15" },
    { name: "Marlon", date: "2026-09-17" },
    { name: "Josh", date: "2026-09-19" },
    { name: "Fabi", date: "2026-09-22" },
    { name: "Carsten", date: "2026-09-24" },
    { name: "Perez", date: "2026-09-27" },
    { name: "Löwe", date: "2026-09-29" },
    { name: "Chris", date: "2026-10-01" },
    { name: "Mateo", date: "2026-10-04" },
    { name: "Nille", date: "2026-10-06" },
    { name: "Sommer", date: "2026-10-08" },
    { name: "Harry", date: "2026-10-13" },
    { name: "Rene", date: "2026-10-15" },
    { name: "Janton", date: "2026-10-20" },
    { name: "Nils", date: "2026-10-23" },
    { name: "Jööl", date: "2026-10-25" },
    { name: "Jannis", date: "2026-10-27" },
    { name: "Melf", date: "2026-10-29" },
    { name: "Jonathan", date: "2026-11-03" },
    { name: "Tim", date: "2026-11-05" },
    { name: "Jule", date: "2026-11-08" },
    { name: "Len", date: "2026-11-10" },
    { name: "Marlon", date: "2026-11-12" },
    { name: "Josh", date: "2026-11-14" },
    { name: "Fabi", date: "2026-11-17" },
    { name: "Carsten", date: "2026-11-19" },
    { name: "Perez", date: "2026-11-22" },
    { name: "Löwe", date: "2026-11-24" },
    { name: "Chris", date: "2026-11-26" },
    { name: "Mateo", date: "2026-11-28" },
    { name: "Nille", date: "2026-12-01" },
    { name: "Sommer", date: "2026-12-03" },
    { name: "Harry", date: "2026-12-06" },
    { name: "Rene", date: "2026-12-08" },
    { name: "Janton", date: "2026-12-10" },
    { name: "Nils", date: "2026-12-13" },
    { name: "Jööl", date: "2026-12-15" },
    { name: "Jannis", date: "2026-12-17" },
    { name: "Melf", date: "2027-01-05" },
    { name: "Jonathan", date: "2027-01-07" },
    { name: "Tim", date: "2027-01-12" },
    { name: "Jule", date: "2027-01-14" },
    { name: "Len", date: "2027-01-19" },
    { name: "Marlon", date: "2027-01-24" },
    { name: "Josh", date: "2027-01-26" },
    { name: "Fabi", date: "2027-01-28" },
    { name: "Carsten", date: "2027-01-30" },
    { name: "Perez", date: "2027-02-02" },
    { name: "Löwe", date: "2027-02-04" },
    { name: "Chris", date: "2027-02-09" },
    { name: "Mateo", date: "2027-02-11" },
    { name: "Nille", date: "2027-02-13" },
    { name: "Sommer", date: "2027-02-16" },
    { name: "Harry", date: "2027-02-18" },
    { name: "Rene", date: "2027-02-21" },
    { name: "Janton", date: "2027-02-23" },
    { name: "Nils", date: "2027-02-25" },
    { name: "Jööl", date: "2027-02-28" },
    { name: "Jannis", date: "2027-03-02" },
    { name: "Melf", date: "2027-03-04" },
    { name: "Jonathan", date: "2027-03-13" },
    { name: "Tim", date: "2027-03-16" },
    { name: "Jule", date: "2027-03-18" },
    { name: "Len", date: "2027-03-20" },
    { name: "Marlon", date: "2027-03-23" },
    { name: "Josh", date: "2027-03-25" },
    { name: "Fabi", date: "2027-03-30" },
    { name: "Carsten", date: "2027-04-01" },
    { name: "Perez", date: "2027-04-06" },
    { name: "Löwe", date: "2027-04-08" },
    { name: "Chris", date: "2027-04-11" },
    { name: "Mateo", date: "2027-04-13" },
    { name: "Nille", date: "2027-04-15" },
    { name: "Sommer", date: "2027-04-17" }
];


export const kassenVerlauf = [];
export const strafenLogbook = [];
